In [1]:
!uv add numpy

Resolved 34 packages in 584ms
Checked 33 packages in 41ms


In [3]:
import numpy as np
print(np.__version__)


2.5.1


In [4]:
#!pip list | grep numpy
# windows에는 기본적으로 grep대시 findstr이 탑재되어 있음
!uv  pip list | findstr numpy   

numpy                   2.5.1


In [5]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 31.2 ms
Wall time: 30 ms


499999500000

In [6]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [7]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [8]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [9]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [13]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  
[[5,6][7,8]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\playdata2\AppData\Local\Temp\ipykernel_13904\2883858806.py:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[5,6][7,8]]


TypeError: list indices must be integers or slices, not tuple

In [14]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

['1' '2' '3']


In [15]:
a = np.array(['a', 1, True])
print(a)              # array(['a', '1', 'True'], dtype='<U21')


['a' '1' 'True']


In [18]:
a = np.ones(3)
print(a)          # [0. 0. 0.]

[1. 1. 1.]


In [17]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
a = np.eye(3)
print(a)               # [[1. 0. 0.]
													#[0. 1. 0.]
													#[0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# 1를 시작되는 위치를 지정할 수 있다. (k=1)
a = np.eye(3, 4, k=1) # 3행 4열
print(a)                 # [[0. 1. 0. 0.]
                            #[0. 0. 1. 0.]
                           # [0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
a = np.full((2,2), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)                     # [[1 2][3 4]]

[[1 2]
 [3 4]]


In [23]:
a = np.full((2,2), [[1],[2]])  # np.full(shape, fill_value)
print(a)                    # [[1 1][2 2]]

[[1 1]
 [2 2]]


In [25]:
a = np.empty(3)
print(a)         # [1. 1. 1.]

[1. 1. 1.]


In [26]:
a = np.linspace(0, 49)
print(a)             # [0.  1.  2. 3. ... 49.]    

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [27]:
a = np.linspace(0, 5)
print(a)            # [0. 0.10204082  ...  4.89795918 5.]

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [28]:
# 기본 사용법
# 0부터 9까지의 숫자 배열 생성
arr = np.arange(10)
print(arr)              # [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [30]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.zeros_like(a)
print(b)

```
[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]
 ```

SyntaxError: invalid syntax (107519198.py, line 7)

In [31]:
# 동일한 난수 결과 발생을 위한 난수 시드 값 고정
np.random.seed(42)

num = np.random.rand(2, 3)
print(num)

# 평균 0, 표준편차 1 구조를 만족하는 3행 3열의 정규분포 매트릭스 빌드
normal_dist_matrix = np.random.randn(3, 3)
print(normal_dist_matrix)   # [[-0.23415337 ... 0.24196227]]


# 1부터 46 미만의 범위에서 무작위 로또 번호 숫자를 닮은 6개 정수 생성
lotto_numbers = np.random.randint(1, 46, size=6)
print(lotto_numbers)     # [39 29 15 43  8 21]

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


In [32]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [33]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # True
print(a == b)             # False

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
1658593044608
1658593127168
False
True
[10, 2, 3]
[10, 2, 3]


In [34]:
import copy

a = [[1,2,3]]
# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a) 

print(a[0] is b[0])        # 메모리 주소 False
print(a[0] == b[0])        # 값 True

b[0][0] = 10

print(a[0] is b[0])         # 메모리 주소 False
print(a[0] == b[0])         # 값 False

print(a)                    # [[1, 2, 3]]
print(b)                    # [[10, 2, 3]]

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


In [35]:
a = [1,2,3]
b = a[:]
print(a)                      # [1,2,3]
print(b)                      # [1,2,3]

b[0] = 10
print(a)                      # [1, 2, 3]
print(b)                      # [10, 2, 3]

a = [[1,2,3]]
b = a[:]
print(a is b)                 # False
print(a == b)                 # True

 # 메모리 주소 비교  => 2차원일때 deepcopy 가 발생되지 않음
print(a[0][0] is b[0][0])                    #True
print(a[0][0] == b[0][0])  # 값비교           True


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [36]:
import numpy as np

# 3행 3열 구조의 2차원 기본 배열 정의
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1번 행의 2번 열 데이터 단독 호출 ➔ 값: 6
target_value = arr[1, 2]
print(target_value)  # 출력 결과: 6


6


In [37]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[arr > 5])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [38]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[bool_mask])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [39]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


In [40]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

SyntaxError: invalid syntax (3624996163.py, line 4)

In [43]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
type(...)    # ellipsis

ellipsis

In [45]:
# 숫자 1, 5, 9, 3, 7, 11가져오기
print(a[0, :, 1])              # [1 5 9]

[1 5 9]


In [46]:
# 숫자 1,5,9,3,7,11 가져오기
a[[0], :, [1,3]]


array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [48]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')     
print(f'{arr is dap}')

[1 2 3 4]
메모리 공유 확인:: False
False


In [49]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') 


# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')

arr_2d = arr_1d.reshape(3, 4)
arr_line= np.ravel(arr_2d)

# [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr_line)

#메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d, arr_line)}')



메모리 공유 확인:: True
메모리 공유 확인:: True
[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True


In [50]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.r_[a,b])                              # [[1 2 3]                    [4 5 6]]

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')                      # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3]
 [4 5 6]]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [[1 2 3]
 [4 5 6]]


In [51]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]      

b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]

print(np.r_[a,b])

h_row = np.vstack([a,b])
print(f'h_row:: {h_row}')     # h_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)  # axis = 0
print(f'concat_row:: {concat_row}') # concat_row:: [1 2 3 4 5 6]

a=[1 2 3]
b=[4 5 6]
[1 2 3 4 5 6]
h_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [1 2 3 4 5 6]


In [52]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]

print("행벡터:\n", row_vec)
print("열벡터:\n", col_vec)

```
행벡터:
 [[1 2 3]]
열벡터:
 [[1]
 [2]
 [3]]
 ```
 


SyntaxError: invalid syntax (2734118413.py, line 14)

In [53]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# axis=0 위치에 차원 추가 -> shape: (1, 3)
e0 = np.expand_dims(arr, axis=0)

# axis=1 위치에 차원 추가 -> shape: (3, 1)
e1 = np.expand_dims(arr, axis=1)

print("e0.shape:", e0.shape) # (1, 3)
print("e1.shape:", e1.shape) # (3, 1)

e0.shape: (1, 3)
e1.shape: (3, 1)


In [56]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [57]:
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [58]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)


(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [59]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))

print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [60]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]

print("행벡터:\n", row_vec)
print("열벡터:\n", col_vec)


행벡터:
 [[1 2 3]]
열벡터:
 [[1]
 [2]
 [3]]


In [61]:
import numpy as np

# 1. Shape (4,) 크기의 1차원 배열 생성
arr = np.array([1, 2, 3, 4])

# 2. 스칼라(단일 값) 정의
scalar = 1

# 3. 배열과 스칼라 간의 덧셈 연산 (브로드캐스팅 발생)
#    스칼라 값 '1'이 배열의 크기인 (4,)에 맞게 [1, 1, 1, 1]로 확장되어 각 원소별로 더해집니다.
result = arr + scalar

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(arr)         # 입력 배열 출력 -> 출력: [1 2 3 4]
print(scalar)      # 더해지는 스칼라 값 출력 -> 출력: 1
print(result)      # 연산 결과 출력 -> 출력: [2 3 4 5]

# Shape(모양) 확인
print(arr.shape)   # 입력 배열의 shape -> 출력: (4,)
print(result.shape)# 결과 배열의 shape -> 출력: (4,)

[1 2 3 4]
1
[2 3 4 5]
(4,)
(4,)


In [62]:
import numpy as np

# 1. 2차원 배열 x2 생성 (shape: 3x3)
x2 = np.array([[2, 1, 6],
               [0, 7, 4],
               [5, 3, 2]])

# 2. 정렬 연산
# ① 좌에서 우로 정렬 (axis=1: 행 내부에서 가로 방향 정렬)
sort_axis1 = np.sort(x2, axis=1)

# ② 위에서 아래로 정렬 (axis=0: 열 내부에서 세로 방향 정렬)
sort_axis0 = np.sort(x2, axis=0)

# ③ 아래에서 위로 거꾸로 정렬 (axis=0 정렬 후 행 순서 뒤집기)
sort_axis0_reverse = np.sort(x2, axis=0)[::-1]

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x2)
# 원본 배열 출력:
# [[2 1 6]
#  [0 7 4]
#  [5 3 2]]

# ① np.sort(x2, axis=1) -> 좌에서 우로 정렬
print(sort_axis1)
# 출력:
# [[1 2 6]
#  [0 4 7]
#  [2 3 5]]

# ② np.sort(x2, axis=0) -> 위에서 아래로 정렬
print(sort_axis0)
# 출력:
# [[0 1 2]
#  [2 3 4]
#  [5 7 6]]

# ③ np.sort(x2, axis=0)[::-1] -> 아래에서 위로 거꾸로 정렬
print(sort_axis0_reverse)
# 출력:
# [[5 7 6]
#  [2 3 4]
#  [0 1 2]]

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


In [63]:
import numpy as np

# 1. 1차원 배열 생성 (색인/Index: 0~5)
#    값(Value)   : [5, 4, 3, 2, 1, 0]
#    인덱스(Index): [0, 1, 2, 3, 4, 5]
x = np.array([5, 4, 3, 2, 1, 0])

# 2. 통계 및 조건부 추출 연산
max_val = np.max(x)                 # 최대값
min_val = np.min(x)                 # 최소값
where_idx = np.where(x >= 3)        # 조건(x >= 3)을 만족하는 인덱스 추출
where_val = x[np.where(x >= 3)]     # 조건(x >= 3)에 해당하는 실제 값들 추출

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x)                  # 입력 배열 -> 출력: [5 4 3 2 1 0]

# 1) 최대값 (np.max)
print(max_val)            # 출력: 5

# 2) 최소값 (np.min)
print(min_val)            # 출력: 0

# 3) 조건에 해당하는 인덱스 위치 (np.where(x >= 3))
#    x >= 3 조건(5, 4, 3)을 만족하는 위치의 인덱스 [0, 1, 2] 반환
print(where_idx)          # 출력: (array([0, 1, 2]),)

# 4) 조건에 해당하는 실제 값 (x[np.where(x >= 3)])
#    인덱스 [0, 1, 2]에 위치한 실제 요소들을 추출
print(where_val)          # 출력: [5 4 3]

[5 4 3 2 1 0]
5
0
(array([0, 1, 2]),)
[5 4 3]


In [64]:
 
import numpy as np

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]

# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]

# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

Vector Dot Product:
32

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


In [65]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


In [66]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
